CREATE TABLE [dbo].[COMMON_CODES]
(
	[ID] INT NOT NULL Identity(1,1) PRIMARY KEY,

	--CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL Default(GetDate()),
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,

	[EXPR_DATE] DATETIME DEFAULT(CONVERT(DATE,'9999-12-31')) NOT NULL, 
	[GROUP_CODE] NVARCHAR(64) NOT NULL,  -- MDL001
	[CODE] NVARCHAR(64) NOT NULL,
	[CODE_NAME] NVARCHAR(256) NULL
)
