CREATE TABLE [dbo].[REPORTS]
(
	[REPORT_ID] INT NOT NULL  Identity(1,1) PRIMARY KEY,

	--CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL,
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,

	[STRT_DATE] DATE NULL,
	[END_DATE] DATE NULL,
	[ORGN_NAME] NVARCHAR(50) NULL,
	[PART_NAME] NVARCHAR(255) NULL,
	[USER_NAME] NVARCHAR(255) NULL,
	
	[REPORT_TITLE] NVARCHAR(MAX) NULL,
	[REPORT_CONTENT] NVARCHAR(MAX) NULL,

)
GO


CREATE INDEX [IX_REPORTS_01] ON [dbo].[REPORTS] ([STRT_DATE] DESC, [END_DATE] DESC, [CREATOR] )
GO

CREATE INDEX [IX_REPORTS_02] ON [dbo].[REPORTS] ([STRT_DATE] DESC, [END_DATE] DESC, [ORGN_NAME] )
GO
