CREATE TABLE [dbo].[USERS]
(
	[USER_ID]  INT NOT NULL  Identity(1,1) PRIMARY KEY,
	
	--CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL,
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,
	
	[EMAIL] NVARCHAR(128) NOT NULL,
	[PASSWORD] NVARCHAR(128) NOT NULL,
	[USER_NAME] NVARCHAR(128) NULL,
	[PART_NAME] NVARCHAR(128) NULL,
	[ORGN_NAME] NVARCHAR(128) NULL
)
GO



CREATE UNIQUE INDEX [IX_USERS_01] ON [dbo].[USERS] ([EMAIL])

GO

CREATE INDEX [IX_USERS_02] ON [dbo].[USERS] ([ORGN_NAME])
