CREATE TABLE [dbo].[VOTE_QUESTION]
(
	[VOTE_ID] INT NOT NULL Identity(1,1) PRIMARY KEY,

    --CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL Default(GetDate()),
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,

	[QUESTION] NVARCHAR(MAX),
	[EFCT_DATE] DATE NULL,
	[EXPR_DATE] DATE NULL,

	[CANDIDATE_ID] INT,
)
GO


CREATE INDEX [IX_VOTE_QUESTION_01] ON [dbo].[VOTE_QUESTION] ([EXPR_DATE], [EFCT_DATE])
