CREATE TABLE [dbo].[VOTE_PARTICIPANT]
(
	[PARTICIPANT_ID] INT NOT NULL Identity(1,1) PRIMARY KEY,
	    --CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL Default(GetDate()),
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,

	[VOTE_ID] INT NOT NULL,
	[ORGN_NAME] NVARCHAR(255) NULL, -- ALL OR ORGN
	[EMAIL] NVARCHAR(255) NULL      -- ALL OR EMAIL

)
GO


CREATE INDEX [IX_VOTE_PARTICIPANT_01] ON [dbo].[VOTE_PARTICIPANT] ([VOTE_ID], [EMAIL])

GO

CREATE INDEX [IX_VOTE_PARTICIPANT_02] ON [dbo].[VOTE_PARTICIPANT] ([EMAIL])
