CREATE TABLE [dbo].[VOTE_QUESTION]
(
	[VOTE_ID] INT NOT NULL Identity(1,1) PRIMARY KEY,

    --CONTROL FIELD
	[CREATOR] NVARCHAR(255) NOT NULL,
	[CREATION_DATE] DATETIME NOT NULL Default(GetDate()),
	[MODIFIER] NVARCHAR(255) NULL,
	[MODIFICATION_DATE] DATETIME NULL,
	[API_NAME] NVARCHAR(255) NULL,

	[QUESTION] NVARCHAR(MAX),
	[VOTE_STAT]         NVARCHAR (2)   NULL, -- 01 : 진행중, 02 : 삭제, 03 : 완료
	[EFCT_DATE] DATE NULL,
	[EXPR_DATE] DATE NULL,

	[CANDIDATE_ID] INT,
)
GO


CREATE INDEX [IX_VOTE_QUESTION_01] ON [dbo].[VOTE_QUESTION] ([VOTE_STAT], [EFCT_DATE], [EXPR_DATE])
